<?php
echo "<div class='card'><div class='card-body'>";
echo "<h2 class='text-center'>Kelola Kegiatan</h2>";
echo "</div></div><hr>";
$i = 0;

if ($kegiatans->count() > 0) {
    ?>
    <table class="table table-bordered table-hover text-center align-bottom">
        <thead class="thead bg-secondary text-white ">
        <tr>
            <th class="align-middle">#</th>
            <th class="align-middle">Judul</th>
            <th class="align-middle">Deskripsi</th>
            <th class="align-middle">Waktu</th>
            <th class="align-middle">Tanggal</th>
            <th class="align-middle">Lokasi</th>
            <th class="align-middle">Last Modified</th>
            <th class="align-middle">Foto Kegiatan</th>

            <th><a href="#modal-tambah" class="btn btn-primary" data-toggle="modal" data-placement="top" title="Tambah kegiatan baru"><i class="fas fa-plus" aria-hidden="true"></i></a></th>
        </tr>
        </thead>
        <tbody class="bg-white">
        <?php foreach ($kegiatans as $kegiatan) { $i++ ?>
            <tr>
                <td class="align-middle"><?php echo $i ?></td>
                <td class="align-middle"><?php echo $kegiatan->kegiatan_nama; ?></td>
                <td class="align-middle text-left"><?php echo $kegiatan->kegiatan_deskripsi; ?></td>
                <td class="align-middle"><?php echo $kegiatan->kegiatan_waktu; ?></td>
                <td class="align-middle"><?php echo $kegiatan->kegiatan_tanggal; ?></td>
                <td class="align-middle"><?php echo $kegiatan->kegiatan_lokasi; ?></td>
                <td class="align-middle"><?php echo $kegiatan->kegiatan_updated; ?></td>
                <td class="align-middle"><img class="img-responsive center-block" 
                    height="150" width="100" 
                    src="data:image/jpeg;base64,<?php echo $kegiatan->getKegiatanFoto() ?>">
                </td>
                <td class="align-middle" >
                    <a style="width:45px;" href="#modal-edit" class="btn btn-info" data-toggle="modal" data-placement="top" title="Edit Kegiatan"><i class="fas fa-edit" aria-hidden="true"></i></a>
                    <a style="width:45px; margin: 5px auto" href="#modal-delete" class="btn btn-danger" data-toggle="modal" data-placement="top" title="Hapus Kegiatan"><i class="far fa-trash-alt" aria-hidden="true"></i></a>
                    <?php echo '<a href="/kegiatan/lihatpendaftar/', $kegiatan->kegiatan_id, '"class="btn btn-warning text-white" data-placement="top" title="Lihat Peserta"><i class="fas fa-users" aria-hidden="true"></i></a>'; ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>
<!-- Modal -->
<div class="modal fade" id="modal-tambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Tambah Kegiatan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <?php
        echo $this->tag->form(
            [
                "kegiatan/addkegiatan",
                "autocomplete" => "off",
                "class" => "form-horizontal",
                "enctype" => "multipart/form-data"
            ]
        );
       ?>  
        <div class="modal-body">
            <div class="row">
                    <div class="col-12 form-group">
                        <label for="kegiatan_nama">Nama Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_nama", "class" => "form-control", "required" => "1"]); ?>
                    </div>

                    <div class="col-6 form-group">
                        <label for="kegiatan_waktu">Waktu Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_waktu", "class" => "form-control", "required" => "1"]); ?>
                    </div>
                    
                    <div class="col-6 form-group">
                        <label for="kegiatan_tanggal">Tanggal Kegiatan</label>
                        <input id="kegiatan_tanggal" name="kegiatan_tanggal" class="datepicker form-control" data-date-format="dd/mm/yyyy">
                    </div>
                    
                    <div class="col-6 form-group">
                        <label for="kegiatan_lokasi">Lokasi Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_lokasi", "class" => "form-control", "required" => "1"]); ?>
                    </div>

                    <div class="col-6 form-group">
                        <label for="kegiatan_foto">Foto Kegiatan</label>
                        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "kegiatan_foto"]) ?>
                    </div>

                    <div class="col-12 form-group">
                        <label for="kegiatan_deskripsi">Deskripsi Kegiatan</label>
                        <?php echo $this->tag->textArea(["kegiatan_deskripsi", "class" => "form-control", "required" => "1"]); ?>
                    </div>
                    
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <?php echo $this->tag->submitButton(["Submit", "class" => "btn btn-primary"]), PHP_EOL; ?>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Edit Kegiatan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- <?php echo $this->tag->form("kegiatan/editkegiatan/".$kegiatan->kegiatan_id); ?> -->
      <?php
        echo $this->tag->form(
          [
            "kegiatan/editkegiatan/".$kegiatan->kegiatan_id,
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data"
          ]
        );
       ?> 
        <div class="modal-body">
            <div class="row">
                    <div class="col-12 form-group">
                        <label for="kegiatan_nama">Nama Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_nama", "class" => "form-control", "required" => "1", "value" => $kegiatan->kegiatan_nama]); ?>
                    </div>

                    <div class="col-6 form-group">
                        <label for="kegiatan_waktu">Waktu Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_waktu", "class" => "form-control", "required" => "1", "value" => $kegiatan->kegiatan_waktu]); ?>
                    </div>
                    
                    <div class="col-6 form-group">
                        <label for="kegiatan_tanggal">Waktu Kegiatan</label>
                        <?php echo '<input class="datepicker form-control" id="kegiatan_tanggal" name="kegiatan_tanggal" data-date-format="dd/mm/yyyy" value ="',$kegiatan->kegiatan_tanggal ,'" />'; ?>
                    </div>
                    
                    <div class="col-6 form-group">
                        <label for="kegiatan_lokasi">Lokasi Kegiatan</label>
                        <?php echo $this->tag->textField(["kegiatan_lokasi", "class" => "form-control", "required" => "1", "value" => $kegiatan->kegiatan_lokasi]); ?>
                    </div>

                    <div class="col-6 form-group">
                        <label for="kegiatan_foto">Foto Kegiatan</label>
                        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "kegiatan_foto", "required" => 1]); ?>
                    </div>

                    <div class="col-12 form-group">
                        <label for="kegiatan_deskripsi">Deskripsi Kegiatan</label>
                        <?php echo $this->tag->textArea(["kegiatan_deskripsi", "class" => "form-control", "required" => "1", "value" => $kegiatan->kegiatan_deskripsi]); ?>
                    </div>
                    
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <?php echo $this->tag->submitButton(["Submit", "class" => "btn btn-primary"]), PHP_EOL; ?>
        </div>
      </form>
    </div>
  </div>
</div>
        
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Hapus Kegiatan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <?php echo "Apakah anda yakin akan menghapus kegiatan <strong>", $kegiatan->kegiatan_nama, "</strong>"; ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <?php
            echo $this->tag->linkTo([
                "/kegiatan/hapuskegiatan/".$kegiatan->kegiatan_id,
                'Ya ',
                "class" => "btn btn-danger",
                "data-toggle" =>"tooltip",
                "data-placement" => "top",
                'title' => "Hapus Kegiatan"
            ]);
        ?>
      </div>
    </div>
  </div>
</div>        
