<?php
echo "<div class='card'><div class='card-body'>";
echo "<h2 class='text-center'>Kegiatan Masjid</h2>";
echo "</div></div>";
$i = 0;

echo '<div id="accordion">';

if ($kegiatans->count() > 0) {
    foreach ($kegiatans as $kegiatan) { $i++
?>
    <div class="card" style="margin:5px auto">
        <!-- <div class="card-body collapsed" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo"> -->
        <?php echo '<div class="card-header collapsed" id="heading', $i, '" data-toggle="collapse" data-target="#collapse', $i ,'">'; ?>
            <h5 class="mb-0"><?php echo $kegiatan->kegiatan_nama; ?></h5>
        </div>
        <?php echo '<div id="collapse', $i,'" class="collapse show" aria-labelledby="heading',$i,'">'; ?>
            <div class="card-body row align-middle">
                <img class="col-2 img-responsive center-block" 
                                height="180" width="100" 
                                src="data:image/jpeg;base64,<?php echo $kegiatan->getKegiatanFoto() ?>">
                <div class="col-10 row">
                    <p class="col-12"><?php echo $kegiatan->kegiatan_deskripsi; ?></p>
                    <p class="col-4"><i class="fas fa-clock">&nbsp;</i><?php echo $kegiatan->kegiatan_waktu; ?></p>
                    <p class="col-4"><i class="far fa-calendar-alt">&nbsp;</i><?php echo $kegiatan->kegiatan_tanggal; ?></p>
                    <p class="col-4"><i class="fas fa-map-marker-alt">&nbsp;</i><?php echo $kegiatan->kegiatan_lokasi; ?></p>
                    <?php
                        echo $this->tag->linkTo([
                            "/kegiatan/detailkegiatan/".$kegiatan->kegiatan_id,
                            'Read More',
                            "class" => "col-12 btn btn-info align-middle",
                            "data-toggle" =>"tooltip",
                            "data-placement" => "top",
                            'title' => "Read more",
                            'style' => "padding-top: 15px;"
                        ]);
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php
    }
}
?>