
<h2>User Profile</h2>
<hr>
<div class="card">
    <div class="card-body">
        <?php echo $this->tag->form("user/editedprofile"); ?>

        <div class="form-group">
            <label for="name">Full Name</label>
            <?php echo $this->tag->textField(['name', "class" => "form-control", "value" => $this->session->get('name') ]); ?>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <?php echo $this->tag->emailField(["email", "class" => "form-control", "value" => $this->session->get('email') ]); ?>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $this->tag->passwordField(["password", "class" => "form-control", "value" => $this->session->get('password'), "required" => "1"]); ?>
        </div>

        <div class="form-group">
            <label for="address">Addres</label>
            <?php echo $this->tag->textField(["address", "class" => "form-control", "value" => $this->session->get('address') ]); ?>
        </div>
        
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <?php echo $this->tag->textField(["phone", "class" => "form-control", "value" => $this->session->get('phone') ]); ?>
        </div>

        <?= $this->tag->linkTo(["user/profile", 'Cancel Edit', "class" => "btn btn-danger"]); 
        echo "&nbsp", $this->tag->submitButton(["Save", "class" => "btn btn-primary"]); ?>

    </form>
    </div>
</div>
