
<h2>Login</h2>
<hr>
<div class="card">
    <div class="card-body">
    <?php echo $this->tag->form("user/login"); ?>

        <div class="form-group">
            <label for="email">Email</label>
            <?php echo $this->tag->emailField(['email', "class" => "form-control"]); ?>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $this->tag->passwordField(['password', "class" => "form-control"]); ?>
        </div>


        <?php 
            echo $this->tag->submitButton(["Login", "class" => "btn btn-primary"]), PHP_EOL; 
            echo "<br><br>", "Don't have an account yet? &nbsp";
            echo $this->tag->linkTo("/signup", "Sign Up");
        ?>

    </form>
    </div>
</div>

