<h2>Sign up</h2><hr>

<div class="card">
    <div class="card-body">
    
<p><?php echo $this->flashSession->output() ?></p>

<?php echo $this->tag->form("user/register"); ?>

        <div class="form-group">
            <label for="name">Full Name</label>
            <?php echo $this->tag->textField(['name', "class" => "form-control"]); ?>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <?php echo $this->tag->emailField(["email", "class" => "form-control"]); ?>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $this->tag->passwordField(["password", "class" => "form-control", "required" => "1"]); ?>
        </div>

        <div class="form-group">
            <label for="address">Addres</label>
            <?php echo $this->tag->textField(["address", "class" => "form-control"]); ?>
        </div>
        
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <?php echo $this->tag->textField(["phone", "class" => "form-control"]); ?>
        </div>
        

        <div class="form-group">
        <?php 
            echo $this->tag->submitButton(["Register", "class" => "btn btn-primary"]), PHP_EOL; 
            echo "<br><br>", "Already have an account? &nbsp";
            echo $this->tag->linkTo("/user/loginpage", "Login");
        ?>
        </div>

    </form>

    </div>
</div>
