<h2>Donasi</h2><hr>

<div class="card">
    <div class="card-body">
    
<p><?php echo $this->flashSession->output() ?></p>

<?php echo $this->tag->form("uang/adduang"); ?>

        <div class="row">
            <div class="col-12 text-center">
                <img src="https://www.qrcode-monkey.com/img/default-preview-qr.svg" alt="">
            </div>
            <div class="col form-group">
                <label for="uang_pengirim">Pengirim</label>
                <?php echo $this->tag->textField(['uang_pengirim', "class" => "form-control", 'placeholder' => 'Hamba Allah', 'value' => 'Hamba Allah']); ?>
            </div>

            <div class="col form-group">
                <label for="uang_nominal">Nominal (Rp)</label>
                <!-- <?php echo $this->tag->selectStatic(['uang_nominal',["Kebersihan" => "Kebersihan", "Keamanan" => "Keamanan", "Kegiatan" => "Kegiatan", "Pelayanan" => "Pelayanan"], "class" => "form-control"]); ?> -->
                <?php echo $this->tag->numericField(["uang_nominal", "class" => "form-control", "step" => "1000", "min" => "0"]); ?>
            </div>

            <div class="col-12 form-group">
                <label for="uang_pesan">Pesan</label>
                <?php echo $this->tag->textArea(["uang_pesan", "class" => "form-control"]); ?>
            </div>
            
            <div class="col-12 form-group">
            <?php 
                echo $this->tag->submitButton(["Submit", "class" => "btn btn-primary"]), PHP_EOL; 
            ?>
            </div>
        </div>
        
    </form>

    </div>
</div>
